server:
  servlet:
    context-path: /comp208-group60
  port: 8081

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://45.62.123.144:3306/comp208?characterEncoding=utf-8
    username: COMP208
    password: mT8RCCeZbPsT2XjE
  mvc:
    hiddenmethod:
      filter:
        enabled: true

mybatis:
  mapper-locations: classpath:com/group60/mapper/*.xml
  type-aliases-package: com.group60.entity
logging:
  level:
    root: info
    com.group60: debug
